[theme]
primaryColor = "#8B4513" # Saddle Brown: Represents the wood and leather used in medieval monastic buildings
backgroundColor = "#F5DEB3" # Wheat: A light, earthy tone to represent parchment
secondaryBackgroundColor = "#D2B48C" # Tan: Another earthy tone, slightly darker to differentiate from the primary background
textColor = "#FAEBD7" # Antique White: An alabaster shade to provide good contrast against the brown background
font = "serif" # Serif: A traditional and scholarly feel suitable for historical content
